// Generates src/generated-icons.ts from the platform registry in
// src/platforms.tsx. For each platform it emits the raw inner SVG markup and
// viewBox so the plugin can build `data:image/svg+xml` URIs at runtime for the
// CSS-drawn corner badges (no React needed on the cards themselves).
//
// Run automatically by `pnpm build`. Re-run manually with:
//   node scripts/gen-icons.mjs
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = fs.readFileSync(path.join(ROOT, "src/platforms.tsx"), "utf8");

// ---- parse the PLATFORMS array (single source of truth) ----
const arrStart = src.indexOf("export const PLATFORMS: Platform[] = [");
const arrEnd = src.indexOf("\n];", arrStart);
if (arrStart < 0 || arrEnd < 0) throw new Error("Could not locate PLATFORMS array");
const body = src.slice(arrStart, arrEnd);

const platforms = [];
const blockRe = /\{\s*id:\s*"([^"]+)",[\s\S]*?\},/g;
let m;
while ((m = blockRe.exec(body))) {
  const block = m[0];
  const get = (re) => (block.match(re) || [])[1] ?? null;
  platforms.push({
    id: get(/id:\s*"([^"]+)"/),
    icon: get(/icon:\s*([^,\n]+),/).trim(),
  });
}

// ---- react-icons raw data extraction ----
const faTxt = fs.readFileSync(path.join(ROOT, "node_modules/react-icons/fa6/index.mjs"), "utf8");
const siTxt = fs.readFileSync(path.join(ROOT, "node_modules/react-icons/si/index.mjs"), "utf8");
function extractIcon(name) {
  const file = name.startsWith("Fa") ? faTxt : siTxt;
  const re = new RegExp("function " + name + "\\s*\\(props\\)\\s*\\{[\\s\\S]*?GenIcon\\(([\\s\\S]*?)\\)\\(props\\)");
  const mm = file.match(re);
  if (!mm) throw new Error("react-icon not found: " + name);
  return JSON.parse(mm[1]);
}
function renderChildren(node) {
  return (node.child || [])
    .map((c) => {
      const attr = Object.entries(c.attr || {})
        .filter(([k]) => k !== "role")
        .map(([k, v]) => `${k}="${v}"`)
        .join(" ");
      const kids = renderChildren(c);
      return `<${c.tag} ${attr}>${kids}</${c.tag}>`;
    })
    .join("");
}
function reactIcon(name) {
  const data = extractIcon(name);
  return { viewBox: data.attr.viewBox || "0 0 24 24", inner: renderChildren(data) };
}

// ---- custom glyphs (must match src/glyphs.tsx exactly) ----
const CUSTOM = {
  SwitchGlyph:
    '<path fill-rule="evenodd" clip-rule="evenodd" d="M9 2.5H6.5A3.5 3.5 0 0 0 3 6v12a3.5 3.5 0 0 0 3.5 3.5H9V2.5ZM6.4 6.6a1.3 1.3 0 1 0 0 2.6 1.3 1.3 0 0 0 0-2.6ZM15 2.5h2.5A3.5 3.5 0 0 1 21 6v12a3.5 3.5 0 0 1-3.5 3.5H15V2.5Zm2.6 12.1a1.3 1.3 0 1 0 0 2.6 1.3 1.3 0 0 0 0-2.6Z"/>',
  DPadGlyph:
    '<path d="M9.5 3a1 1 0 0 0-1 1v4.5H4a1 1 0 0 0-1 1v4.9a1 1 0 0 0 1 1h4.5V20a1 1 0 0 0 1 1h4.9a1 1 0 0 0 1-1v-4.6H20a1 1 0 0 0 1-1V9.5a1 1 0 0 0-1-1h-4.6V4a1 1 0 0 0-1-1H9.5Z"/>',
  CartridgeGlyph:
    '<path fill-rule="evenodd" clip-rule="evenodd" d="M6 2a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2v-3h1a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-1V4a2 2 0 0 0-2-2H6Zm1.5 3h6v3h-6V5Z"/>',
};

// ---- text glyph (mirrors makeTextGlyph in src/glyphs.tsx) ----
function textGlyph(label) {
  const len = label.length;
  const fontSize = len <= 2 ? 12 : len === 3 ? 10 : len === 4 ? 8.5 : 7.5;
  const textLength = len <= 2 ? "" : len === 3 ? ' textLength="17"' : len === 4 ? ' textLength="20"' : ' textLength="21"';
  const spacing = len <= 2 ? "0.5px" : "0px";
  const inner =
    `<text x="12" y="12.5" text-anchor="middle" dominant-baseline="central" ` +
    `font-size="${fontSize}" font-weight="800"${textLength} lengthAdjust="spacingAndGlyphs" ` +
    `style="font-family:'Motiva Sans','Segoe UI',system-ui,sans-serif;letter-spacing:${spacing}">${label}</text>`;
  return { viewBox: "0 0 24 24", inner };
}

function resolve(iconExpr) {
  const t = iconExpr.match(/makeTextGlyph\("([^"]+)"\)/);
  if (t) return textGlyph(t[1]);
  if (CUSTOM[iconExpr]) return { viewBox: "0 0 24 24", inner: CUSTOM[iconExpr] };
  return reactIcon(iconExpr);
}

const entries = platforms.map((p) => {
  const g = resolve(p.icon);
  return `  ${JSON.stringify(p.id)}: { viewBox: ${JSON.stringify(g.viewBox)}, inner: ${JSON.stringify(g.inner)} },`;
});

const out =
  `// AUTO-GENERATED by scripts/gen-icons.mjs — DO NOT EDIT BY HAND.\n` +
  `// Regenerate with: node scripts/gen-icons.mjs (runs automatically on \`pnpm build\`).\n` +
  `// Raw SVG glyph data for every platform, used to build CSS badge data-URIs.\n\n` +
  `export interface GlyphData {\n  /** SVG viewBox for this glyph. */\n  viewBox: string;\n  /** Inner SVG markup (paths/text) with no fill, so it inherits the chosen colour. */\n  inner: string;\n}\n\n` +
  `export const PLATFORM_GLYPHS: Record<string, GlyphData> = {\n${entries.join("\n")}\n};\n`;

fs.writeFileSync(path.join(ROOT, "src/generated-icons.ts"), out);
console.log(`Generated src/generated-icons.ts with ${platforms.length} platform glyphs.`);
